/**
 * Este analizador implementa la gramática y el análisis semántico para un 
 * lenguaje de programación. Proporciona soporte para:
 *
 * - Análisis sintáctico mediante YACC/BYACCJ
 * - Verificación de tipos estática
 * - Manejo de ámbitos y símbolos
 * - Generación de código intermedio
 * - Control de errores y recuperación
 *
 * El parser trabaja en conjunto con:
 * - Analizador léxico (JFlex)
 * - Tabla de símbolos
 * - Sistema de tipos
 * - Generador de código intermedio
 * 
 * @author steve-quezada
 * @author etnicst
 */

%{
// Importaciones del sistema
import java.io.*;              // Entrada/salida estándar
import java.util.Stack;        // Estructuras de pila
import java.util.List;         // Listas dinámicas
import java.util.ArrayList;    // Implementación de listas

// Importaciones del proyecto
import src.Analizador_Sintactico_BYACCJ.tablas.Tablas.*;    // Gestión de tablas
import src.Analizador_Sintactico_BYACCJ.pilas.Pilas.*;      // Gestión de pilas
import src.Analizador_Sintactico_BYACCJ.utils.Colors;       // Utilidades de formato
import src.Analizador_Sintactico_BYACCJ.jflex.Token;        // Definición de tokens
import src.Analizador_Sintactico_BYACCJ.jflex.ClaseLexica;  // Tipos de tokens

/**
 * Clase AtribExp - Atributos para Expresiones
 *
 * Mantiene la información semántica asociada a cada no terminal
 * durante el análisis sintáctico y la generación de código.
 */
class AtribExp {
    String dir;         // Dirección temporal del resultado
    int tipo;           // Tipo semántico
    String codigo;      // Código intermedio generado
    boolean esArray;    // Indicador de acceso a array
    String base;        // Dirección base para arrays/structs
    String id;          // Nombre del identificador
    List<Object> lista; // Lista de argumentos/parámetros

    /**
     * Constructor por defecto
     * Inicializa todos los campos con valores predeterminados seguros
     */
    AtribExp() {
        this.dir = "";
        this.tipo = TablaTipos.T_ERROR;
        this.codigo = "";
        this.esArray = false;
        this.base = "";
        this.id = "";
        this.lista = new ArrayList<>();
    }

    /**
     * Constructor de copia
     * @param other Instancia a copiar
     */
    AtribExp(AtribExp other) {
        this.dir = other.dir;
        this.tipo = other.tipo;
        this.codigo = other.codigo;
        this.esArray = other.esArray;
        this.base = other.base;
        this.id = other.id;
    }
}

//#############################################
//## file: Parser.java
//## Generated by Byacc/j
//#############################################

/**
 * BYACC/J Semantic Value for parser: Parser
 * This class provides some of the functionality
 * of the yacc/C 'union' directive
 */
class ParserVal {

  Token id;          /* Para identificadores */
  Token val;         /* Para valores literales */
  AtribExp AtribExp; /* Para expresiones y otros no terminales */
  AtribExp lista;    /* Para listas (argumentos, parámetros) */

  public ParserVal(Token value) {
    this.id = value;
    this.val = value;
  }

  public ParserVal(AtribExp value) {
    this.AtribExp = value;
    this.lista = value;
  }

  /**
   * integer value of this 'union'
   */
  public int ival;

  /**
   * double value of this 'union'
   */
  public double dval;

  /**
   * string value of this 'union'
   */
  public String sval;

  /**
   * object value of this 'union'
   */
  public Object obj;

  // #############################################
  // ## C O N S T R U C T O R S
  // #############################################
  /**
   * Initialize me without a value
   */
  public ParserVal() {
  }

  /**
   * Initialize me as an int
   */
  public ParserVal(int val) {
    ival = val;
  }

  /**
   * Initialize me as a double
   */
  public ParserVal(double val) {
    dval = val;
  }

  /**
   * Initialize me as a string
   */
  public ParserVal(String val) {
    sval = val;
  }

  /**
   * Initialize me as an Object
   */
  public ParserVal(Object val) {
    obj = val;
  }
}
// end class

// #############################################
// ## E N D O F F I L E
// #############################################

%}

// Sección de declaraciones Yacc
/* TOKENS Y PRECEDENCIAS */

// Símbolo inicial que define el punto de entrada de la gramática
%start programa

/* TOKENS PARA TIPOS DE DATOS BÁSICOS
 * Cada token representa un tipo de dato fundamental del lenguaje
 */
%token INT     // Tipo entero
%token FLOAT   // Tipo punto flotante
%token DOUBLE  // Tipo doble precisión
%token COMPLEX // Tipo número complejo
%token RUNE    // Tipo carácter Unicode
%token VOID    // Tipo vacío
%token STRING  // Tipo cadena de caracteres
%token STRUCT  // Tipo estructura
%token PTR     // Tipo puntero

/* Palabras reservadas */
%token FUNC IF ELSE WHILE DO BREAK RETURN SWITCH CASE DEFAULT
%token PRINT SCAN TRUE FALSE PROTO

/* Identificadores y literales */
%token <id> ID
%token <val> LIT_ENTERO
%token <val> LIT_FLOAT LIT_DOUBLE LIT_COMPLEX LIT_STRING LIT_RUNE

/* Operadores */
%token OR AND IGUAL DIFERENTE MENOR MENORIGUAL MAYORIGUAL MAYOR
%token MAS MENOS POR DIV MOD DIVINT NOT ASIG

/* Delimitadores */
%token PARI PARD CORI CORD LLAI LLAD COMA PYC PUNTO DOSP

/* Precedencia y asociatividad */
%left OR
%left AND
%left IGUAL DIFERENTE
%left MENOR MENORIGUAL MAYORIGUAL MAYOR
%left MAS MENOS
%left POR DIV MOD DIVINT
%right NOT
%right UMENOS

/* Tipos para no terminales */
%type <AtribExp> programa tipo basico compuesto exp
%type <AtribExp> parte_izquierda decl_var puntero lista_args
%type <lista> argumentos parametros lista_param
%type <AtribExp> lista_var arreglo estructurado
%type <AtribExp> bloque declaraciones instrucciones
%type <AtribExp> casos caso opcion sentencia
%type <AtribExp> localizacion predeterminado
%type <AtribExp> decl_proto decl_func

%%

/* REGLAS DE PRODUCCIÓN
 
 * Cada regla incluye:
 * 1. Documentación detallada
 * 2. Acciones semánticas
 * 3. Generación de código
 * 4. Manejo de errores
 */

/* Estructura básica del programa */
programa : 
        {
            // Inicialización de estructuras semánticas
            tablaTipos = new TablaTipos();
            pilaTs = new PilaTs();
            pilaDir = new PilaDir();
            dir = 0;
            // Crear tabla de símbolos global
            pilaTs.push(new TablaSimbolos());
            $$ = new AtribExp();
        }
        decl_proto decl_var decl_func
        { 
            $$ = new AtribExp();
            if (currentToken != null && currentToken.getClaseLexica() == ClaseLexica.EOF) {
                System.out.println("\nAnálisis sintáctico completado exitosamente.");
            }
        }
        ;

/* Declaraciones de prototipos */
decl_proto : PROTO tipo ID PARI argumentos PARD PYC
        {
            $$ = new AtribExp();
            // Registrar el prototipo en la tabla de símbolos global
            if (!pilaTs.bottom().existe($3.getLexema())) {
                pilaTs.bottom().add($3.getLexema(), -1, $2.tipo, "func", $5.lista);
                // Simplificar el mensaje mostrado
                printSemanticInfo("Declaración de Prototipo", 
                    "Nombre: " + $3.getLexema(), Colors.INDIGO);
            } else {
                yyerror("El prototipo " + $3.getLexema() + " ya fue declarado");
            }
        }
        decl_proto
        {
            $$ = new AtribExp();
        }
        | /* epsilon */
        {
            $$ = new AtribExp();
        }
        ;

/* Declaraciones de variables */
decl_var : tipo lista_var PYC
        {
            $$ = new AtribExp();
            $$.tipo = $1.tipo;
            // Actualizar tabla de símbolos con el tipo correcto
            for (String id : listaVariables) {
                if (pilaTs.top().existe(id)) {
                    pilaTs.top().setTipo(id, $1.tipo);
                }
            }
            procesarDeclaracionVariables($1.tipo);
        }
        decl_var
        {
            $$ = new AtribExp();
        }
        | /* epsilon */
        {
            $$ = new AtribExp();
        }
        ;

// Tipos de datos
tipo : basico compuesto
     {
         $$ = new AtribExp();
         if ($2.tipo != -1) { // Si hay un tipo compuesto
             $$.tipo = $2.tipo;
         } else {
             $$.tipo = $1.tipo; // Propagar el tipo básico
         }
         // Guardar el tipo actual para usarlo en lista_var
         yylval.AtribExp = $$;
     }
     | STRUCT LLAI 
     {
         // Crear nueva tabla de símbolos para la estructura
         pilaTs.push(new TablaSimbolos());
         pilaDir.push(dir);
         dir = 0;
     }
     decl_var LLAD
     {
         $$ = new AtribExp();
         TablaSimbolos tsStruct = pilaTs.top();
         pilaTs.pop();
         $$.tipo = tablaTipos.add("struct", tsStruct);
         dir = pilaDir.pop();
     }
     | puntero
     {
         $$ = new AtribExp();
         $$.tipo = $1.tipo;
     }
     ;

// Punteros
puntero : PTR basico
        {
            $$ = new AtribExp();
            $$.tipo = $2.tipo;
        }
        ;

// Tipos básicos
basico : INT    
       { 
           $$ = new AtribExp();
           $$.tipo = TablaTipos.T_INT; 
       }
       | FLOAT  
       { 
           $$ = new AtribExp();
           $$.tipo = TablaTipos.T_FLOAT; 
       }
       | DOUBLE 
       { 
           $$ = new AtribExp();
           $$.tipo = TablaTipos.T_DOUBLE; 
       }
       | COMPLEX 
       { 
           $$ = new AtribExp();
           $$.tipo = TablaTipos.T_COMPLEX; 
       }
       | RUNE   
       { 
           $$ = new AtribExp();
           $$.tipo = TablaTipos.T_RUNE; 
       }
       | VOID   
       { 
           $$ = new AtribExp();
           $$.tipo = TablaTipos.T_VOID; 
       }
       | STRING 
       { 
           $$ = new AtribExp();
           $$.tipo = TablaTipos.T_STRING; 
       }
       ;

// Tipos compuestos
compuesto : CORI LIT_ENTERO CORD compuesto
         {
             $$ = new AtribExp();
             if ($2.valor <= 0) {
                 yyerror("El tamaño del arreglo debe ser mayor a cero");
                 $$.tipo = TablaTipos.T_ERROR;
             } else {
                 $$.tipo = tablaTipos.add($2.valor, $4.tipo, "array");
             }
             $$.dir = "";
         }
         | /* epsilon */
         {
             $$ = new AtribExp();
             $$.tipo = -1;
         }
         ;

// Lista de variables
lista_var : lista_var COMA ID
         {
             if (!pilaTs.top().existe($3.getLexema())) {
                 $$ = new AtribExp();
                 $$.tipo = $1.tipo;
                 pilaTs.top().add($3.getLexema(), dir, $1.tipo, "var", null);
                 dir += tablaTipos.getTam($1.tipo);
             } else {
                 yyerror("La variable " + $3.getLexema() + " ya fue declarada");
             }
             listaVariables.add($3.getLexema());
         }
         | ID
         {
             if (!pilaTs.top().existe($1.getLexema())) {
                 $$ = new AtribExp();
                 int tipoActual = yylval.AtribExp != null ? yylval.AtribExp.tipo : TablaTipos.T_ERROR;
                 $$.tipo = tipoActual;
                 pilaTs.top().add($1.getLexema(), dir, tipoActual, "var", null);
                 dir += tablaTipos.getTam(tipoActual);
             } else {
                 yyerror("La variable " + $1.getLexema() + " ya fue declarada");
             }
             listaVariables.add($1.getLexema());
         }
         ;

/* Declaraciones de funciones */
decl_func : FUNC tipo ID 
         {
             // Pre-verificación de la función
             if (!pilaTs.bottom().existe($3.getLexema())) {
                 pilaTs.bottom().add($3.getLexema(), -1, $2.tipo, "func", new ArrayList<>());
             }
         }
         PARI argumentos PARD bloque
         {
             // Validación y configuración de la función
             if (pilaTs.bottom().existe($3.getLexema())) {
                 // Actualizar la información de argumentos
                 pilaTs.bottom().setInfo($3.getLexema(), $6.lista);
                 
                 // Crear nuevo ámbito para la función
                 pilaTs.push(new TablaSimbolos());
                 pilaDir.push(dir);
                 dir = 0;
                 tipoReturnFunc = $2.tipo;
                 
                 // Registrar los parámetros en el ámbito local
                 if ($6.lista != null) {
                     for (Object arg : $6.lista) {
                         if (arg instanceof Argumento) {
                             Argumento argumento = (Argumento) arg;
                             pilaTs.top().add(argumento.id, dir, argumento.tipo, "param", null);
                             dir += tablaTipos.getTam(argumento.tipo);
                         }
                     }
                 }
                 // Mover la impresión aquí, después de procesar toda la función
                 printSemanticInfo("Declaración de Función", 
                     "Nombre: " + $3.getLexema(), Colors.PINK);
             } else {
                 yyerror("Error interno: La función " + $3.getLexema() + " no fue pre-registrada");
             }
             
             // Cerrar el ámbito de la función
             pilaTs.pop();
             dir = pilaDir.pop();
             $$ = new AtribExp();
         }
         decl_func
         {
             $$ = new AtribExp();
         }
         | /* epsilon */
         {
             $$ = new AtribExp();
         }
         ;

// Argumentos de funciones
argumentos : lista_args
          {
              $$ = new AtribExp();
              $$.lista = $1.lista;
          }
          | /* epsilon */
          {
              $$ = new AtribExp();
              $$.lista = new ArrayList<>();
          }
          ;

// Lista de argumentos
lista_args : lista_args COMA tipo ID
          {
              $$ = new AtribExp();
              $$.lista = new ArrayList<>($1.lista);
              $$.lista.add(new Argumento($4.getLexema(), $3.tipo));
          }
          | tipo ID
          {
              $$ = new AtribExp();
              $$.lista = new ArrayList<>();
              $$.lista.add(new Argumento($2.getLexema(), $1.tipo));
          }
          ;

// Bloque de código
bloque : LLAI declaraciones instrucciones LLAD
       {
           $$ = new AtribExp();
       }
       ;

// Declaraciones
declaraciones : decl_var
              {
                  $$ = new AtribExp();
                  $$.tipo = $1.tipo;
              }
              ;

// Instrucciones
instrucciones : instrucciones sentencia
              {
                  $$ = new AtribExp();
              }
              | sentencia
              {
                  $$ = new AtribExp();
              }
              ;

// Sentencias
sentencia : parte_izquierda ASIG exp PYC
         {
             // Asegurarnos de que ambos tipos estén inicializados
             if ($1.tipo == TablaTipos.T_ERROR) {
                 $1.tipo = TablaTipos.T_INT;
             }
             if ($3.tipo == TablaTipos.T_ERROR) {
                 $3.tipo = TablaTipos.T_INT;
             }

             // Verificar compatibilidad de tipos
             if (sonTiposCompatibles($1.tipo, $3.tipo)) {
                 printSemanticInfo("Verificación de Tipos", 
                     "Tipos compatibles: " + obtenerNombreTipo($1.tipo) + 
                     " = " + obtenerNombreTipo($3.tipo), Colors.OLD_GOLD);
                 
                 $$ = new AtribExp();
                 String valorConvertido = convertirTipo($3.dir, $3.tipo, $1.tipo);
                 
                 if ($1.esArray) {
                     genCode($1.base + "[" + $1.dir + "] = " + valorConvertido);
                 } else {
                     genCode($1.id + " = " + valorConvertido);
                 }
             } else {
                 printSemanticInfo("Error de Tipos", 
                     "Tipos incompatibles: " + obtenerNombreTipo($1.tipo) + 
                     " = " + obtenerNombreTipo($3.tipo), Colors.RED);
                 yyerror("Tipos incompatibles en asignación");
             }
         }
         | IF PARI exp PARD sentencia
         {
             String labelTrue = newLabel();
             String labelFalse = newLabel();
             pilaLabelTrue.push(labelTrue);
             pilaLabelFalse.push(labelFalse);
             
             genCode("if " + $3.dir + " goto " + labelTrue);
             genCode("goto " + labelFalse);
             label(labelTrue);
             label(labelFalse);
             
             pilaLabelTrue.pop();
             pilaLabelFalse.pop();
             $$ = new AtribExp();
         }
         | IF PARI exp PARD sentencia ELSE sentencia
         {
             String labelTrue = newLabel();
             String labelFalse = newLabel();
             String labelNext = newLabel();
             
             pilaLabelTrue.push(labelTrue);
             pilaLabelFalse.push(labelFalse);
             pilaLabelNext.push(labelNext);
             
             genCode("if " + $3.dir + " goto " + labelTrue);
             genCode("goto " + labelFalse);
             label(labelTrue);
             genCode("goto " + labelNext);
             label(labelFalse);
             label(labelNext);
             
             pilaLabelTrue.pop();
             pilaLabelFalse.pop();
             pilaLabelNext.pop();
             $$ = new AtribExp();
         }
         | WHILE PARI exp PARD sentencia
         {
             String labelNext = newLabel();
             String labelTrue = newLabel();
             String labelFalse = newLabel();
             
             pilaLabelNext.push(labelNext);
             pilaLabelTrue.push(labelTrue);
             pilaLabelFalse.push(labelFalse);
             
             label(labelNext);
             genCode("if " + $3.dir + " goto " + labelTrue);
             genCode("goto " + labelFalse);
             label(labelTrue);
             genCode("goto " + labelNext);
             label(labelFalse);
             
             pilaLabelTrue.pop();
             pilaLabelFalse.pop();
             pilaLabelNext.pop();
             $$ = new AtribExp();
         }
         | DO sentencia WHILE PARI exp PARD PYC
         {
             $$ = new AtribExp();
             String labelStart = newLabel();
             label(labelStart);
             genCode("if " + $5.dir + " goto " + labelStart);
         }
         | BREAK PYC
         {
             $$ = new AtribExp();
         }
         | bloque
         {
             $$ = new AtribExp();
         }
         | RETURN exp PYC
         {
             if ($2.tipo == TablaTipos.T_ERROR) {
                 $2.tipo = TablaTipos.T_INT;
             }
             
             if (sonTiposRetornoCompatibles(tipoReturnFunc, $2.tipo)) {
                 $$ = new AtribExp();
                 genCode("return " + convertirTipo($2.dir, $2.tipo, tipoReturnFunc));
             } else {
                 yyerror("Tipo de retorno incompatible. Se esperaba " + 
                     obtenerNombreTipo(tipoReturnFunc) + " pero se encontró " + 
                     obtenerNombreTipo($2.tipo));
             }
         }
         | RETURN PYC
         {
             if (tipoReturnFunc == TablaTipos.T_VOID || tipoReturnFunc == TablaTipos.T_ERROR) {
                 $$ = new AtribExp();
                 genCode("return");
             } else {
                 yyerror("Se esperaba un valor de retorno de tipo " + 
                     obtenerNombreTipo(tipoReturnFunc));
             }
         }
         | SWITCH PARI exp PARD LLAI casos LLAD
         {
             $$ = new AtribExp();
         }
         | PRINT exp PYC
         {
             $$ = new AtribExp();
         }
         | SCAN parte_izquierda PYC
         {
             $$ = new AtribExp();
         }
         ;

// Casos de switch
casos : caso casos
      {
          $$ = new AtribExp();
      }
      | /* epsilon */
      {
          $$ = new AtribExp();
      }
      | predeterminado
      {
          $$ = new AtribExp();
      }
      ;

// Caso de switch
caso : CASE opcion DOSP instrucciones
     {
         $$ = new AtribExp();
     }
     ;

// Opción de caso
opcion : LIT_ENTERO
       {
           $$ = new AtribExp();
           $$.tipo = TablaTipos.T_INT;
       }
       | LIT_RUNE
       {
           $$ = new AtribExp();
           $$.tipo = TablaTipos.T_RUNE;
       }
       ;

// Caso predeterminado
predeterminado : DEFAULT DOSP instrucciones
               {
                   $$ = new AtribExp();
               }
               ;

// Parte izquierda de una asignación
parte_izquierda : ID localizacion
                {
                    $$ = new AtribExp();
                    $$ = $2;
                    $$.id = $1.getLexema();
                    if (!pilaTs.existe($$.id)) {
                        // Si la variable no existe, crearla en el ámbito actual
                        pilaTs.top().add($$.id, dir, TablaTipos.T_INT, "var", null);
                        dir += tablaTipos.getTam(TablaTipos.T_INT);
                    }
                }
                | ID
                {
                    $$ = new AtribExp();
                    $$.id = $1.getLexema();
                    if (!pilaTs.existe($$.id)) {
                        // Si la variable no existe, crearla en el ámbito actual
                        pilaTs.top().add($$.id, dir, TablaTipos.T_INT, "var", null);
                        dir += tablaTipos.getTam(TablaTipos.T_INT);
                    }
                    $$.tipo = pilaTs.getTipo($$.id);
                }
                ;

// Expresiones
exp : exp OR exp                 /* || */
    {
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = max($1.tipo, $3.tipo);
            String α1 = ampliar($1.dir, $1.tipo, $$.tipo);
            String α2 = ampliar($3.dir, $3.tipo, $$.tipo);
            genCode($$.dir + " = " + α1 + " || " + α2);
        } else {
            yyerror("Tipos incompatibles en operación lógica OR");
        }
    }
    | exp AND exp                /* && */
    {
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = max($1.tipo, $3.tipo);
            String α1 = ampliar($1.dir, $1.tipo, $$.tipo);
            String α2 = ampliar($3.dir, $3.tipo, $$.tipo);
            genCode($$.dir + " = " + α1 + " && " + α2);
        } else {
            yyerror("Tipos incompatibles en operación lógica AND");
        }
    }
    | exp AND exp                /* && */
    | exp IGUAL exp              /* == */
    {
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = max($1.tipo, $3.tipo);
            String α1 = ampliar($1.dir, $1.tipo, $$.tipo);
            String α2 = ampliar($3.dir, $3.tipo, $$.tipo);
            genCode($$.dir + " = " + α1 + " == " + α2);
        } else {
            yyerror("Tipos incompatibles en comparación de igualdad");
        }
    }
    | exp DIFERENTE exp          /* != */
    {
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = max($1.tipo, $3.tipo);
            String α1 = ampliar($1.dir, $1.tipo, $$.tipo);
            String α2 = ampliar($3.dir, $3.tipo, $$.tipo);
            genCode($$.dir + " = " + α1 + " != " + α2);
        } else {
            yyerror("Tipos incompatibles en comparación de diferencia");
        }
    }
    | exp MENOR exp              /* < */
    {
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = max($1.tipo, $3.tipo);
            String α1 = ampliar($1.dir, $1.tipo, $$.tipo);
            String α2 = ampliar($3.dir, $3.tipo, $$.tipo);
            genCode($$.dir + " = " + α1 + " < " + α2);
        } else {
            yyerror("Tipos incompatibles en comparación menor que");
        }
    }
    | exp MENORIGUAL exp         /* <= */
    {
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = max($1.tipo, $3.tipo);
            String α1 = ampliar($1.dir, $1.tipo, $$.tipo);
            String α2 = ampliar($3.dir, $3.tipo, $$.tipo);
            genCode($$.dir + " = " + α1 + " <= " + α2);
        } else {
            yyerror("Tipos incompatibles en comparación menor o igual que");
        }
    }
    | exp MAYORIGUAL exp         /* >= */
    {
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = max($1.tipo, $3.tipo);
            String α1 = ampliar($1.dir, $1.tipo, $$.tipo);
            String α2 = ampliar($3.dir, $3.tipo, $$.tipo);
            genCode($$.dir + " = " + α1 + " >= " + α2);
        } else {
            yyerror("Tipos incompatibles en comparación menor o igual que");
        }
    }
    | exp MAYOR exp              /* > */
    {
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = max($1.tipo, $3.tipo);
            String α1 = ampliar($1.dir, $1.tipo, $$.tipo);
            String α2 = ampliar($3.dir, $3.tipo, $$.tipo);
            genCode($$.dir + " = " + α1 + " > " + α2);
        } else {
            yyerror("Tipos incompatibles en comparación menor que");
        }
    }
    | exp MAS exp
    {
        initializeVariablesIfNeeded($1, $3);
        
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = max($1.tipo, $3.tipo);
            String α1 = ampliar($1.dir, $1.tipo, $$.tipo);
            String α2 = ampliar($3.dir, $3.tipo, $$.tipo);
            genCode($$.dir + " = " + α1 + " + " + α2);
        } else {
            yyerror("Tipos incompatibles en suma");
            $$ = new AtribExp();
            $$.tipo = TablaTipos.T_ERROR;
        }
    }
    | exp MENOS exp
    {
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = max($1.tipo, $3.tipo);
            String α1 = ampliar($1.dir, $1.tipo, $$.tipo);
            String α2 = ampliar($3.dir, $3.tipo, $$.tipo);
            genCode($$.dir + " = " + α1 + " - " + α2);
        } else {
            yyerror("Tipos incompatibles en resta");
        }
    }
    | exp POR exp
    {
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = max($1.tipo, $3.tipo);
            String α1 = ampliar($1.dir, $1.tipo, $$.tipo);
            String α2 = ampliar($3.dir, $3.tipo, $$.tipo);
            genCode($$.dir + " = " + α1 + " * " + α2);
        } else {
            yyerror("Tipos incompatibles en multiplicación");
        }
    }
    | exp DIV exp
    {
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = max($1.tipo, $3.tipo);
            String α1 = ampliar($1.dir, $1.tipo, $$.tipo);
            String α2 = ampliar($3.dir, $3.tipo, $$.tipo);
            genCode($$.dir + " = " + α1 + " / " + α2);
        } else {
            yyerror("Tipos incompatibles en división");
        }
    }
    | exp MOD exp                /* % */
    {
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = max($1.tipo, $3.tipo);
            genCode($$.dir + " = " + $1.dir + " % " + $3.dir);
        } else {
            yyerror("Tipos incompatibles en operación módulo");
        }
    }
    | exp DIVINT exp            /* // */
    {
        if (tablaTipos.sonCompatibles($1.tipo, $3.tipo)) {
            $$ = new AtribExp();
            $$.dir = nuevaTemporal();
            $$.tipo = TablaTipos.T_INT;
            genCode($$.dir + " = " + $1.dir + " / " + $3.dir);
        } else {
            yyerror("Tipos incompatibles en división entera");
        }
    }
    | NOT exp                   /* ! */
    {
        $$ = new AtribExp();
        $$.dir = nuevaTemporal();
        $$.tipo = TablaTipos.T_INT;
        genCode($$.dir + " = !" + $2.dir);
    }
    | MENOS exp %prec UMENOS    /* - (unario) */
    {
        $$ = new AtribExp();
        $$.dir = nuevaTemporal();
        $$.tipo = $2.tipo;
        genCode($$.dir + " = -" + $2.dir);
    }
    | PARI exp PARD
    {
        $$ = new AtribExp();
        $$.dir = $2.dir;
        $$.tipo = $2.tipo;
    }
    | ID localizacion
    {
        $$ = new AtribExp();
        $$.dir = nuevaTemporal();
        $$.tipo = $2.tipo;
        genCode($$.dir + " = " + $1.getLexema() + "[" + $2.dir + "]");
    }
    | TRUE
    {
        $$ = new AtribExp();
        $$.dir = "1";
        $$.tipo = TablaTipos.T_INT;
    }
    | FALSE
    {
        $$ = new AtribExp();
        $$.dir = "0";
        $$.tipo = TablaTipos.T_INT;
    }
    | LIT_STRING                /* literal_cadena */
    {
        $$ = new AtribExp();
        $$.dir = $1.getLexema();
        $$.tipo = TablaTipos.T_STRING;
    }
    | LIT_RUNE                  /* literal_runa */
    {
        $$ = new AtribExp();
        $$.dir = $1.getLexema();
        $$.tipo = TablaTipos.T_RUNE;
    }
    | LIT_ENTERO                /* literal_entera */
    {
        $$ = new AtribExp();
        $$.dir = $1.getLexema();
        $$.tipo = TablaTipos.T_INT;
    }
    | LIT_FLOAT                 /* literal_flotante */
    {
        $$ = new AtribExp();
        $$.dir = $1.getLexema();
        $$.tipo = TablaTipos.T_FLOAT;
    }
    | LIT_DOUBLE                /* literal_doble */
    {
        $$ = new AtribExp();
        $$.dir = $1.getLexema();
        $$.tipo = TablaTipos.T_DOUBLE;
    }
    | LIT_COMPLEX               /* literal_compleja */
    {
        $$ = new AtribExp();
        $$.dir = $1.getLexema();
        $$.tipo = TablaTipos.T_COMPLEX;
    }
    | ID PARI parametros PARD
    {
        $$ = new AtribExp();
        if (pilaTs.bottom().existe($1.getLexema())) {
            if (pilaTs.bottom().getClase($1.getLexema()).equals("func")) {
                List<Object> argsFunc = pilaTs.bottom().getArgs($1.getLexema());
                if (sonParametrosCompatibles(argsFunc, $3.lista)) {
                    $$.dir = nuevaTemporal();
                    $$.tipo = pilaTs.bottom().getTipo($1.getLexema());
                    genCode($$.dir + " = call " + $1.getLexema() + ", " + 
                           ($3.lista != null ? $3.lista.size() : 0));
                } else {
                    yyerror("Los parámetros no coinciden con la declaración de la función " + $1.getLexema());
                    $$.tipo = TablaTipos.T_ERROR;
                }
            } else {
                yyerror("El identificador " + $1.getLexema() + " no es una función");
                $$.tipo = TablaTipos.T_ERROR;
            }
        } else {
            yyerror("Función " + $1.getLexema() + " no declarada");
            $$.tipo = TablaTipos.T_ERROR;
        }
    }
    | ID
    {
        $$ = new AtribExp();
        boolean found = false;
        
        // Buscar en todos los ámbitos
        for (int i = pilaTs.size() - 1; i >= 0; i--) {
            if (pilaTs.get(i).existe($1.getLexema())) {
                $$.tipo = pilaTs.get(i).getTipo($1.getLexema());
                $$.dir = $1.getLexema();
                found = true;
                break;
            }
        }
        
        // Si no se encuentra, crear la variable en el ámbito actual
        if (!found) {
            $$.tipo = TablaTipos.T_INT;
            $$.dir = $1.getLexema();
            // Agregar a la tabla de símbolos actual
            pilaTs.top().add($1.getLexema(), dir, $$.tipo, "var", null);
            dir += tablaTipos.getTam($$.tipo);
        }
    }
    | ID localizacion
    {
        $$ = new AtribExp();
        $$.dir = nuevaTemporal();
        $$.tipo = $2.tipo;
        genCode($$.dir + " = " + $2.base + "[" + $2.dir + "]");
    }
    ;

// Parámetros de funciones
parametros : lista_param
          {
              $$ = $1;
          }
          | /* epsilon */
          {
              $$ = new AtribExp();
              $$.lista = new ArrayList<>();
          }
          ;

// Lista de parámetros
lista_param : lista_param COMA exp
           {
               $$ = new AtribExp();
               $$.lista = new ArrayList<>($1.lista);
               $$.lista.add($3.tipo);
               genCode("param " + $3.dir);
           }
           | exp
           {
               $$ = new AtribExp();
               $$.lista = new ArrayList<>();
               $$.lista.add($1.tipo);
               genCode("param " + $1.dir);
           }
           ;

// Localización de variables
localizacion : arreglo
             {
                 $$ = new AtribExp();
                 $$ = $1;
             }
             | estructurado
             {
                 $$ = new AtribExp();
                 $$ = $1;
             }
             ;

// Arreglos
arreglo : ID CORI exp CORD
        {
            $$ = new AtribExp();
            boolean found = false;
            int tipo = -1;
            
            // Buscar primero en el ámbito local
            if (pilaTs.top().existe($1.getLexema())) {
                tipo = pilaTs.top().getTipo($1.getLexema());
                found = true;
            }
            // Si no se encuentra, buscar en el ámbito global
            else if (pilaTs.bottom().existe($1.getLexema())) {
                tipo = pilaTs.bottom().getTipo($1.getLexema());
                found = true;
            }
            
            if (found) {
                if (tablaTipos.esArray(tipo)) {
                    if ($3.tipo == TablaTipos.T_INT) {
                        $$.base = $1.getLexema();
                        $$.tipo = tablaTipos.getTipoBase(tipo);
                        int tam = tablaTipos.getTam($$.tipo);
                        $$.dir = nuevaTemporal();
                        genCode($$.dir + " = " + $3.dir + " * " + tam);
                        $$.esArray = true;
                    } else {
                        yyerror("El índice del arreglo debe ser entero");
                        $$.tipo = TablaTipos.T_ERROR;
                    }
                } else {
                    yyerror("La variable " + $1.getLexema() + " no es un arreglo");
                    $$.tipo = TablaTipos.T_ERROR;
                }
            } else {
                yyerror("Variable " + $1.getLexema() + " no declarada");
                $$.tipo = TablaTipos.T_ERROR;
            }
        }
         // Arreglos con acceso anidado
        | arreglo CORI exp CORD
        {
            $$ = new AtribExp();
            if (tablaTipos.esArray($1.tipo)) {
                if ($3.tipo == TablaTipos.T_INT) {
                    $$.base = $1.base;
                    $$.tipo = tablaTipos.getTipoBase($1.tipo);
                    int tam = tablaTipos.getTam($$.tipo);
                    String temp = nuevaTemporal();
                    $$.dir = nuevaTemporal();
                    genCode(temp + " = " + $3.dir + " * " + tam);
                    genCode($$.dir + " = " + $1.dir + " + " + temp);
                    $$.esArray = true;
                } else {
                    yyerror("El índice del arreglo debe ser entero");
                    $$.tipo = TablaTipos.T_ERROR;
                }
            } else {
                yyerror("El arreglo no puede ser indexado tantas veces");
                $$.tipo = TablaTipos.T_ERROR;
            }
        }
        ;

// Estructuras
estructurado : estructurado PUNTO ID
             {
                 $$ = new AtribExp();
                 if (tablaTipos.esStruct($1.tipo)) {
                     TablaSimbolos ts = tablaTipos.getTablaSimbolos($1.tipo);
                     if (ts.existe($3.getLexema())) {
                         $$.dir = nuevaTemporal();
                         genCode($$.dir + " = " + $1.dir + " + " + ts.getDir($3.getLexema()));
                         $$.base = $1.base;
                         $$.tipo = ts.getTipo($3.getLexema());
                     } else {
                         yyerror("El campo " + $3.getLexema() + " no existe en la estructura");
                         $$.tipo = TablaTipos.T_ERROR;
                     }
                 } else {
                     yyerror("No se puede usar el operador punto, el identificador no es una estructura");
                     $$.tipo = TablaTipos.T_ERROR;
                 }
             }
             | ID
             {
                 $$ = new AtribExp();
                 if (pilaTs.top().existe($1.getLexema())) {
                     $$.tipo = pilaTs.top().getTipo($1.getLexema());
                     $$.base = $1.getLexema();
                     $$.dir = "0";
                 } else if (pilaTs.bottom().existe($1.getLexema())) {
                     $$.tipo = pilaTs.bottom().getTipo($1.getLexema());
                     $$.base = $1.getLexema();
                     $$.dir = "0";
                 } else {
                     yyerror("Variable " + $1.getLexema() + " no declarada");
                     $$.tipo = TablaTipos.T_ERROR;
                 }
             }
             ;

%%

/* CÓDIGO DE SOPORTE
 *
 * Implementación de todas las funciones auxiliares
 * necesarias para el análisis semántico y la generación de código
 */

// Variables globales para el análisis semántico
private TablaTipos tablaTipos;
private PilaTs pilaTs;
private PilaDir pilaDir;
private int dir;
private int tipoReturnFunc;

// Pilas para control de flujo
private Stack<String> pilaLabelTrue = new Stack<>();
private Stack<String> pilaLabelFalse = new Stack<>();
private Stack<String> pilaLabelNext = new Stack<>();
private int labelCount = 0;
private int tempCount = 0;
private Lexer lexer;
private Token currentToken;
private List<String> listaVariables = new ArrayList<>();
private boolean hasErrors = false;

/**
 * Genera una nueva etiqueta única para el control de flujo
 * @return String Nueva etiqueta en formato
 */
private String newLabel() {
    String label = "L" + (++labelCount);
    Colors.println("  • Nueva etiqueta: " + label, Colors.GRAY_LIGHT);
    return label;
}

/**
 * Genera y registra una línea de código intermedio
 * @param code Instrucción de código intermedio a generar
 */
private void genCode(String code) {
    Colors.println("  ├─ " + code, Colors.CYAN);
}

/**
 * Imprime una etiqueta de control de flujo
 * @param label Etiqueta a imprimir
 */
private void label(String label) {
    System.out.println(label + ":");
}

/**
 * Genera una nueva variable temporal
 * @return String Nombre de la nueva variable temporal
 */
private String nuevaTemporal() {
    String temp = "t" + (++tempCount);
    Colors.println("  │ Nueva temporal: " + temp, Colors.GRAY_LIGHT);
    return temp;
}

/**
 * Realiza la ampliación de tipos para conversiones implícitas
 * @param valor Valor a convertir
 * @param tipoOrigen Tipo original del valor
 * @param tipoDestino Tipo al que se debe convertir
 * @return String Expresión con la conversión de tipo
 */
private String ampliar(String valor, int tipoOrigen, int tipoDestino) {
    if (tipoOrigen == tipoDestino) return valor;
    return String.format("(%s)%s", tablaTipos.getName(tipoDestino), valor);
}

/**
 * Determina el tipo resultante de una operación entre dos tipos
 * @param tipo1 Primer tipo
 * @param tipo2 Segundo tipo
 * @return int Tipo resultante según las reglas de promoción
 */
private int max(int tipo1, int tipo2) {
    return tablaTipos.getTipoResultante(tipo1, tipo2);
}

/**
 * Constructor del parser
 * Inicializa el analizador léxico y las estructuras necesarias
 * @param input Flujo de entrada para el análisis
 */
public Parser(Reader input) {
    lexer = new Lexer(input);
    Colors.println("\n=== Inicio del Análisis ===", Colors.HIGH_INTENSITY + Colors.BLUE);
    Colors.println("1. Inicializando analizador sintáctico...", Colors.CYAN);
    Colors.println("2. Configurando tablas y estructuras...", Colors.CYAN);
    tipoReturnFunc = TablaTipos.T_ERROR;
}

/**
 * Reporta un error sintáctico
 * @param msg Mensaje de error
 */
private void yyerror(String msg) {
    error(msg, (currentToken != null ? currentToken.getLinea() : -1));
}

/**
 * Procesa y reporta un error detallado
 * @param msg Mensaje de error
 * @param linea Número de línea donde ocurrió el error
 */
private void error(String msg, int linea) {
    hasErrors = true;
    String lineaStr = (linea != -1 ? String.valueOf(linea) : "?");
    String token = (currentToken != null ? currentToken.getLexema() : "null");
    
    // Calcular la longitud máxima para el marco
    int maxLength = Math.max(
        Math.max(
            ("Error: " + msg).length(),
            ("Línea: " + lineaStr).length()
        ),
        ("Token: " + token).length()
    ) + 4;

    String border = "╔" + "═".repeat(maxLength) + "╗";
    String bottomBorder = "╚" + "═".repeat(maxLength) + "╝";

    // Imprimir el mensaje de error
    Colors.println("\n" + border, Colors.RED + Colors.HIGH_INTENSITY);
    Colors.println("║ " + padString("Error Sintáctico", maxLength-2) + " ║", Colors.RED);
    Colors.println("║ " + padString("Línea: " + lineaStr, maxLength-2) + " ║", Colors.RED);
    Colors.println("║ " + padString("Error: " + msg, maxLength-2) + " ║", Colors.RED);
    Colors.println("║ " + padString("Token: " + token, maxLength-2) + " ║", Colors.RED);
    Colors.println(bottomBorder, Colors.RED + Colors.HIGH_INTENSITY);

    // Imprimir mensaje de compilación fallida
    printBox("Compilación Fallida", new String[]{
        "El análisis ha finalizado con errores",
        "Revise los mensajes anteriores"
    }, Colors.RED);

    // Terminar el programa con código de error
    System.exit(1);
}

/**
 * Formatea y muestra un cuadro de mensaje
 * @param title Título del cuadro
 * @param content Contenido a mostrar
 * @param color Color para el formato
 */
private void printBox(String title, String[] content, String color) {
    int maxLength = title.length();
    for (String line : content) {
        maxLength = Math.max(maxLength, line.length());
    }
    maxLength += 4;

    String border = "╔" + "═".repeat(maxLength) + "╗";
    String middleBorder = "╠" + "═".repeat(maxLength) + "╣";
    String bottomBorder = "╚" + "═".repeat(maxLength) + "╝";

    Colors.println("\n" + border, color);
    Colors.println("║ " + padString(title, maxLength-2) + " ║", color);
    Colors.println(middleBorder, color);
    
    for (String line : content) {
        Colors.println("║ " + padString(line, maxLength-2) + " ║", color);
    }
    
    Colors.println(bottomBorder, color);
}

/**
 * Verifica si hay errores en el análisis
 * @return boolean true si se encontraron errores, false en caso contrario
 */
public boolean hasErrors() {
    return hasErrors;
}

/**
 * Rellena una cadena con espacios hasta alcanzar la longitud especificada
 * @param str Cadena a rellenar
 * @param length Longitud deseada
 * @return String Cadena rellenada con espacios
 */
private String padString(String str, int length) {
    return String.format("%-" + length + "s", str);
}

/**
 * Obtiene el siguiente token del analizador léxico
 * @return int Código del token o 0 para EOF, -1 en caso de error
 */
private int yylex() {
    try {
        currentToken = lexer.yylex();
        if (currentToken == null || currentToken.getClaseLexica() == ClaseLexica.EOF) {
            return 0;
        }
        yylval = new ParserVal(currentToken);
        return currentToken.getClaseLexica().ordinal() + 257;
    } catch (IOException e) {
        Colors.println("Error de lectura: " + e.getMessage(), Colors.RED);
        return -1;
    }
}

// Método principal
public static void main(String args[]) {
    if (args.length < 1) {
        System.err.println("Uso: java Parser <archivo_entrada>");
        System.exit(1);
    }
    
    try {
        Parser parser = new Parser(new FileReader(args[0]));
        parser.yyparse();
    } catch (FileNotFoundException e) {
        System.err.println("Error: No se puede abrir el archivo " + args[0]);
    }
}

// Clases de soporte para atributos
class AtributosExp {
    String dir;
    int tipo;
    boolean esArray;
    String base;
    String id;
    
    AtributosExp(String dir, int tipo) {
        this.dir = dir;
        this.tipo = tipo;
        this.esArray = false;
    }
}

class Argumento {
    String id;
    int tipo;

    Argumento(String id, int tipo) {
        this.id = id;
        this.tipo = tipo;
    }
}

// Métodos de procesamiento semántico
private void procesarDeclaracionVariables(int tipo) {
    if (listaVariables.isEmpty()) return;

    for (String id : listaVariables) {
        String tipoStr = obtenerNombreTipo(tipo);
        if (tipo == TablaTipos.T_ERROR || tipo == -1) {
            tipo = TablaTipos.T_INT;
            tipoStr = "int";
        }
        
        // Usar el mismo formato que Declaración de Prototipo
        printSemanticInfo("Declaración de Variable", 
            "Nombre: " + id + 
            "\nTipo: " + tipoStr, 
            Colors.MINT);
    }
    
    listaVariables.clear();
}

/**
 * Inicializa variables si no están definidas
 * @param exp1 Primera expresión a inicializar
 * @param exp2 Segunda expresión a inicializar
 */
private void initializeVariablesIfNeeded(AtribExp exp1, AtribExp exp2) {
    if (exp1.tipo == TablaTipos.T_ERROR) {
        exp1.tipo = TablaTipos.T_INT;
    }
    if (exp2.tipo == TablaTipos.T_ERROR) {
        exp2.tipo = TablaTipos.T_INT;
    }
}

/**
 * Verifica la compatibilidad entre dos tipos
 * @param tipo1 Primer tipo a comparar
 * @param tipo2 Segundo tipo a comparar
 * @return boolean true si los tipos son compatibles
 */
private boolean sonTiposCompatibles(int tipo1, int tipo2) {
    if (tipo1 == TablaTipos.T_ERROR || tipo2 == TablaTipos.T_ERROR) {
        tipo1 = tipo1 == TablaTipos.T_ERROR ? TablaTipos.T_INT : tipo1;
        tipo2 = tipo2 == TablaTipos.T_ERROR ? TablaTipos.T_INT : tipo2;
    }

    String tipo1Str = obtenerNombreTipo(tipo1);
    String tipo2Str = obtenerNombreTipo(tipo2);
    
    // Solo imprimir la verificación una vez y en el lugar correcto
    if (tipo1 == tipo2) {
        return true;
    }

    if (esNumerico(tipo1) && esNumerico(tipo2)) {
        // Imprimir mensaje de conversión implícita solo cuando realmente ocurre
        if (tipo1 != tipo2) {
            printSemanticInfo("Verificación de Tipos", 
                "Conversión numérica implícita: " + tipo1Str + " → " + tipo2Str, 
                Colors.OLD_GOLD);
        }
        return true;
    }

    return false;
}

/**
 * Determina si un tipo es numérico
 * @param tipo Tipo a verificar
 * @return boolean true si es un tipo numérico
 */
private boolean esNumerico(int tipo) {
    return tipo == TablaTipos.T_INT || 
           tipo == TablaTipos.T_FLOAT || 
           tipo == TablaTipos.T_DOUBLE || 
           tipo == TablaTipos.T_COMPLEX;
}

/**
 * Determina si un tipo es booleano
 * @param tipo Tipo a verificar
 * @return boolean true si es tipo booleano
 */
private boolean esBooleano(int tipo) {
    // Considerar TRUE y FALSE como tipos booleanos
    return tipo == TablaTipos.T_BOOL;
}

/**
 * Realiza la conversión entre tipos
 * @param valor Valor a convertir
 * @param tipoOrigen Tipo original
 * @param tipoDestino Tipo destino
 * @return String Expresión con la conversión
 */
private String convertirTipo(String valor, int tipoOrigen, int tipoDestino) {
    if (tipoOrigen == tipoDestino) return valor;
    
    // Manejo especial para conversiones específicas
    if (esNumerico(tipoOrigen) && esNumerico(tipoDestino)) {
        return "(" + obtenerNombreTipo(tipoDestino) + ")" + valor;
    }
    
    return valor;
}

/**
 * Obtiene el nombre legible de un tipo
 * @param tipo Identificador del tipo
 * @return String Nombre del tipo
 */
private String obtenerNombreTipo(int tipo) {
    switch (tipo) {
        case TablaTipos.T_INT: return "int";
        case TablaTipos.T_FLOAT: return "float";
        case TablaTipos.T_DOUBLE: return "double";
        case TablaTipos.T_COMPLEX: return "complex";
        case TablaTipos.T_RUNE: return "rune";
        case TablaTipos.T_STRING: return "string";
        case TablaTipos.T_BOOL: return "bool";
        case TablaTipos.T_VOID: return "void";
        case TablaTipos.T_ERROR: return "tipo no definido";
        default:
            // Para tipos compuestos (arrays y structs)
            if (tablaTipos != null) {
                if (tablaTipos.esArray(tipo)) {
                    int tipoBase = tablaTipos.getTipoBase(tipo);
                    return "array de " + obtenerNombreTipo(tipoBase);
                }
                if (tablaTipos.esStruct(tipo)) {
                    return "struct";
                }
            }
            return "tipo desconocido_" + tipo;
    }
}

/**
 * Verifica la compatibilidad de parámetros en llamadas a función
 * @param argsDeclarados Lista de argumentos en la declaración
 * @param argsLlamada Lista de argumentos en la llamada
 * @return boolean true si los parámetros son compatibles
 */
private boolean sonParametrosCompatibles(List<Object> argsDeclarados, List<Object> argsLlamada) {
    if (argsDeclarados == null && (argsLlamada == null || argsLlamada.isEmpty())) {
        return true;
    }
    if (argsDeclarados == null || argsLlamada == null) {
        return false;
    }
    if (argsDeclarados.size() != argsLlamada.size()) {
        return false;
    }

    for (int i = 0; i < argsDeclarados.size(); i++) {
        Object argDeclarado = argsDeclarados.get(i);
        Object argLlamada = argsLlamada.get(i);

        if (argDeclarado instanceof Argumento) {
            Argumento arg = (Argumento) argDeclarado;
            int tipoDeclarado = arg.tipo;
            int tipoLlamada = (argLlamada instanceof Integer) ? (Integer) argLlamada : TablaTipos.T_ERROR;
            
            if (!sonTiposCompatibles(tipoDeclarado, tipoLlamada)) {
                return false;
            }
        } else {
            return false;
        }
    }
    return true;
}

/**
 * Verifica la compatibilidad en tipos de retorno
 * @param tipoEsperado Tipo de retorno declarado
 * @param tipoActual Tipo de retorno actual
 * @return boolean true si los tipos son compatibles
 */
private boolean sonTiposRetornoCompatibles(int tipoEsperado, int tipoActual) {
    // Si los tipos son iguales
    if (tipoEsperado == tipoActual) return true;

    // Si el tipo esperado no está definido, permitir cualquier tipo
    if (tipoEsperado == TablaTipos.T_ERROR) return true;

    // Para tipos numéricos, permitir conversiones implícitas
    if (esNumerico(tipoEsperado) && esNumerico(tipoActual)) {
        // Evitar pérdida de precisión
        if (getTamanoTipo(tipoEsperado) >= getTamanoTipo(tipoActual)) {
            return true;
        }
    }

    // Casos especiales
    if (tipoEsperado == TablaTipos.T_RUNE && tipoActual == TablaTipos.T_INT) return true;
    if (tipoEsperado == TablaTipos.T_INT && tipoActual == TablaTipos.T_RUNE) return true;

    return false;
}

/**
 * Obtiene el tamaño en bytes de un tipo
 * @param tipo Tipo a consultar
 * @return int Tamaño en bytes
 */
private int getTamanoTipo(int tipo) {
    switch (tipo) {
        case TablaTipos.T_INT: return 4;
        case TablaTipos.T_FLOAT: return 4;
        case TablaTipos.T_DOUBLE: return 8;
        case TablaTipos.T_COMPLEX: return 16;
        case TablaTipos.T_RUNE: return 4;
        default: return 0;
    }
}

/**
 * Procesa la declaración de una función
 * @param nombre Nombre de la función
 * @param tipoRetorno Tipo de retorno
 * @param args Lista de argumentos
 */
private void procesarFuncion(String nombre, int tipoRetorno, List<Object> args) {
    printSemanticInfo("Declaración de Función", 
        "Nombre: " + nombre + "\n│ Tipo retorno: " + obtenerNombreTipo(tipoRetorno), 
        Colors.PINK);
    
    if (args != null && !args.isEmpty()) {
        Colors.println("│ Parámetros:", Colors.BLUE_LIGHT);
        for (Object arg : args) {
            if (arg instanceof Argumento) {
                Argumento argumento = (Argumento) arg;
                Colors.println("│   • " + argumento.id + ": " + 
                    obtenerNombreTipo(argumento.tipo), Colors.GRAY_LIGHT);
            }
        }
    }
}

/**
 * Registra la entrada a un nuevo ámbito
 * @param tipo Tipo de ámbito
 */
private void entrarAmbito(String tipo) {
    printSemanticInfo("Nuevo Ámbito", tipo, Colors.PLUM);
}

/**
 * Registra la salida de un ámbito
 * @param tipo Tipo de ámbito
 */
private void salirAmbito(String tipo) {
    printSemanticInfo("Salir Ámbito", tipo, Colors.PLUM);
}

/**
 * Verifica si existe un identificador en algún ámbito
 * @param id Identificador a buscar
 * @return boolean true si existe el identificador
 */
public boolean existe(String id) {
    for (int i = pilaTs.size() - 1; i >= 0; i--) {
        if (pilaTs.get(i).existe(id)) {
            return true;
        }
    }
    return false;
}

/**
 * Obtiene el tipo de un identificador
 * @param id Identificador a consultar
 * @return int Tipo del identificador o T_ERROR si no existe
 */
public int getTipo(String id) {
    for (int i = pilaTs.size() - 1; i >= 0; i--) {
        if (pilaTs.get(i).existe(id)) {
            return pilaTs.get(i).getTipo(id);
        }
    }
    return TablaTipos.T_ERROR;
}

private void printSemanticInfo(String fase, String detalle, String color) {
    // Define un ancho mínimo y máximo para la tabla
    int minWidth = 40;  // Ancho mínimo
    int maxWidth = 50;  // Ancho máximo
    
    // Agregar espacios al título
    String tituloFormateado = " " + fase + " ";
    
    // Dividir el detalle en líneas si contiene saltos de línea
    String[] lineas = detalle.split("\n");
    
    // Calcular el ancho necesario (considerando el título con espacios)
    int maxLength = tituloFormateado.length();
    for (String linea : lineas) {
        maxLength = Math.max(maxLength, linea.length());
    }
    
    // Ajustar el ancho dentro de los límites establecidos
    maxLength = Math.min(Math.max(maxLength + 4, minWidth), maxWidth);
    
    // Calcular el padding para centrar el título
    int espaciosTotal = maxLength - tituloFormateado.length();
    int espaciosIzq = espaciosTotal / 2;
    int espaciosDer = espaciosTotal - espaciosIzq;
    
    // Crear bordes
    String bordeTop = "╔" + "═".repeat(espaciosIzq) + tituloFormateado + "═".repeat(espaciosDer) + "╗";
    String bordeMiddle = "╠" + "═".repeat(maxLength) + "╣";
    String bordeBottom = "╚" + "═".repeat(maxLength) + "╝";
    
    // Imprimir la tabla
    Colors.println("\n" + bordeTop, color);
    
    // Imprimir cada línea del detalle centrada
    for (int i = 0; i < lineas.length; i++) {
        if (i > 0) Colors.println(bordeMiddle, color);
        
        // Centrar el contenido
        int espaciosContenido = maxLength - lineas[i].length();
        int espaciosIzqContenido = espaciosContenido / 2;
        int espaciosDerContenido = espaciosContenido - espaciosIzqContenido;
        String lineaCentrada = " ".repeat(espaciosIzqContenido) + lineas[i] + " ".repeat(espaciosDerContenido);
        
        Colors.println("║" + lineaCentrada + "║", color);
    }
    
    Colors.println(bordeBottom, color);
}
